title: PLTea
logo: /assets/img/logo.jpg
description:
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
twitter_url: https://twitter.com/PLteaforplt
google_group_url: https://groups.google.com/g/pltea
slack_url: https://t.co/clxVUPEkPm?amp=1
